refactor: #38 Search 컴포넌트 폴더 위치 변경 (Form의 일종으로 취급)
zockq1/piggymy-frontend-admin pull request #47
Opened 2024-05-22 13:22 UTC by heegu0311

재민님 제안에 따라 폴더 구조를 변경해봤습니다.

2024-05-23 05:33 UTC, zockq1 requested changes

2024-05-23 05:33 UTC, zockq1 commented on src/share/form/item/Dropdown.tsx
> +        <Select.Option value="demo">Demo</Select.Option>
Select.option의 value랑 children을 배열 형태의 props로 받아 map으로 출력하게 하는 것이 어떨까요?

2024-05-24 15:35 UTC, heegu0311 commented on src/share/form/item/Dropdown.tsx
> +        <Select.Option value="demo">Demo</Select.Option>
@zockq1 처리했습니다. 확인 부탁드려요!

2024-05-25 11:34 UTC, zockq1 approved these changes

2024-05-25 12:39 UTC, merged